
/* 회원 테이블 */
DROP TABLE USERS;

CREATE TABLE USERS (
EMAIL           VARCHAR2(50)        PRIMARY KEY,
NICK_NAME       VARCHAR2(30)        NOT NULL,
USER_NO         NUMBER(10)          NOT NULL,
PASSWORD        VARCHAR2(30)        NOT NULL,
PHONE_NO        VARCHAR2(11)        NOT NULL,
BIRTH           VARCHAR2(8)         NOT NULL,
GRADE           NUMBER(1)           NOT NULL,
ADDRESS         VARCHAR2(255)
);

DROP SEQUENCE SEQ_USERS_NO;

CREATE SEQUENCE SEQ_USERS_NO
INCREMENT BY 1
START WITH 1;


COMMENT ON COLUMN USERS.EMAIL            IS '이메일';
COMMENT ON COLUMN USERS.NICK_NAME        IS '닉네임';
COMMENT ON COLUMN USERS.USER_NO          IS '회원번호';
COMMENT ON COLUMN USERS.PASSWORD         IS '비밀번호';
COMMENT ON COLUMN USERS.PHONE_NO         IS '휴대폰번호';
COMMENT ON COLUMN USERS.BIRTH            IS '생년월일';
COMMENT ON COLUMN USERS.GRADE            IS '등급';
COMMENT ON COLUMN USERS.ADDRESS          IS '주소';

/* 와인 테이블 */
DROP TABLE WINE;

CREATE TABLE WINE (
WINE_NO         NUMBER(10)      PRIMARY KEY,
WINE_NAME       VARCHAR2(50)    NOT NULL,
WINE_TYPE       VARCHAR2(10)    NOT NULL,
WINE_COUNTRY    VARCHAR2(50)    NOT NULL,
REG_DATE        DATE            NOT NULL
);

DROP SEQUENCE SEQ_WINE_NO;

CREATE SEQUENCE SEQ_WINE_NO
INCREMENT BY 1
START WITH 1;


COMMENT ON COLUMN WINE.WINE_NO          IS '와인상품번호';
COMMENT ON COLUMN WINE.WINE_NAME        IS '와인명';
COMMENT ON COLUMN WINE.WINE_TYPE        IS '와인종류';
COMMENT ON COLUMN WINE.WINE_COUNTRY     IS '생산국';
COMMENT ON COLUMN WINE.REG_DATE         IS '와인등록일';

/* 와인상세 테이블 */
DROP TABLE WINE_DESCRIPTION;

CREATE TABLE WINE_DESCRIPTION (
WINE_NO             NUMBER(10)          PRIMARY KEY,
WINE_COMPANY        VARCHAR2(50)        NOT NULL,
WINE_ALCOHOL        NUMBER(10)          NOT NULL,
WINE_PRICE          NUMBER(10)          NOT NULL,
WINE_STOCK          NUMBER(5)           NOT NULL,
WINE_IMAGE          VARCHAR2(1000),
WINE_DESCRIPTION    VARCHAR2(2000),
CONSTRAINT FK_WINE_DESCRIPTION FOREIGN KEY(WINE_NO)
REFERENCES WINE(WINE_NO)
);

COMMENT ON COLUMN WINE_DESCRIPTION.WINE_NO                  IS '와인상품번호';
COMMENT ON COLUMN WINE_DESCRIPTION.WINE_COMPANY             IS '제조사';
COMMENT ON COLUMN WINE_DESCRIPTION.WINE_ALCOHOL             IS '도수';
COMMENT ON COLUMN WINE_DESCRIPTION.WINE_PRICE               IS '와인가격';
COMMENT ON COLUMN WINE_DESCRIPTION.WINE_STOCK               IS '재고';
COMMENT ON COLUMN WINE_DESCRIPTION.WINE_IMAGE               IS '이미지';
COMMENT ON COLUMN WINE_DESCRIPTION.WINE_DESCRIPTION         IS '상세설명';


/* 주문 테이블 */
DROP TABLE ORDERS;

CREATE TABLE ORDERS (
ORDER_NO        NUMBER(10)      PRIMARY KEY,
EMAIL           VARCHAR2(50)    NOT NULL,
WINE_NO         NUMBER(10)      NOT NULL,
ADDRESS         VARCHAR2(255)   NOT NULL,
ORDERS          VARCHAR2(100),
ORDER_DATE      DATE            NOT NULL,
CONSTRAINT FK_ORDERS_EMAIL FOREIGN KEY(EMAIL)
REFERENCES USERS(EMAIL),
CONSTRAINT FK_ORDERS_WINE_NO FOREIGN KEY(WINE_NO)
REFERENCES WINE(WINE_NO)
);

DROP SEQUENCE SEQ_ORDERS_NO;

CREATE SEQUENCE SEQ_ORDERS_NO
INCREMENT BY 1
START WITH 1;


COMMENT ON COLUMN ORDERS.ORDER_NO          IS '구매번호';
COMMENT ON COLUMN ORDERS.EMAIL             IS '이메일';
COMMENT ON COLUMN ORDERS.WINE_NO           IS '와인상품번호';
COMMENT ON COLUMN ORDERS.ADDRESS           IS '주소';
COMMENT ON COLUMN ORDERS.ORDERS            IS '주문사항';
COMMENT ON COLUMN ORDERS.ORDER_DATE        IS '주문일';


/* 장바구니 테이블 */
DROP TABLE CART;

CREATE TABLE CART (
CART_NO         NUMBER(10)      PRIMARY KEY,
EMAIL           VARCHAR2(50)    NOT NULL,
WINE_NO         NUMBER(10)       NOT NULL,
CONSTRAINT FK_CART_EMAIL FOREIGN KEY(EMAIL)
REFERENCES USERS(EMAIL),
CONSTRAINT FK_CART_WINE_NO FOREIGN KEY(WINE_NO)
REFERENCES WINE(WINE_NO)
);

DROP SEQUENCE SEQ_CART_NO;

CREATE SEQUENCE SEQ_CART_NO
INCREMENT BY 1
START WITH 1;


COMMENT ON COLUMN CART.CART_NO           IS '장바구니번호';
COMMENT ON COLUMN CART.EMAIL             IS '이메일';
COMMENT ON COLUMN CART.WINE_NO           IS '와인번호';

ALTER TABLE CART
ADD(WINE_COUNT NUMBER(5));			/* CART 테이블 WINE_COUNT 컬럼 추가 */

ALTER TABLE CART
ADD(WINE_TOTAL_PRICE NUMBER(10));	/* CART 테이블 WINE_TOTAL_PRICE 컬럼 추가 */

ALTER TABLE CART
MODIFY WINE_COUNT NOT NULL;			/* CART 테이블 WINE_COUNT 제약조건 NOT NULL로 변경 */

ALTER TABLE CART
MODIFY WINE_TOTAL_PRICE NOT NULL;	/* CART 테이블 WINE_TOTAL_PRICE 제약조건 NOT NULL로 변경 */


COMMENT ON COLUMN CART.WINE_COUNT           IS '와인갯수';
COMMENT ON COLUMN CART.WINE_TOTAL_PRICE     IS '와인총합가격';
